version: "3"

services:
  database:
    image: postgres:alpine
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171
  app:
    build: .
    depends_on:
      - database
      - nsqd
    volumes:
      - .:/go/src/github.com/lokhman/example-users-microservice
      - vendor:/go/src/github.com/lokhman/example-users-microservice/vendor
    ports:
      - 8000:8000
    environment:
      GIN_MODE: debug
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres?sslmode=disable
      NSQ_ADDR: nsqd:4150
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8000/ || exit 1"]
    tty: true

volumes:
  vendor:
  database_data:
    driver: local
